# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VariantDatabase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='aa_af',
            new_name='esp_aa_af',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='ea_af',
            new_name='esp_ea_af',
        ),
    ]
