# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VariantDatabase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
