# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VariantDatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
