# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VariantDatabase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('1', 'New Sample'), ('2', 'Awaiting 1st Check'), ('3', 'Awaiting 2nd Check'), ('4', 'Complete')], max_length=1),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='status',
            field=models.CharField(choices=[('1', 'New Worksheet'), ('2', 'Awaiting 1st Check'), ('3', 'Awaiting 2nd Check'), ('4', 'Complete')], max_length=1),
        ),
    ]
