# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VariantDatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_name',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
