# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VariantDatabase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='asn_af',
        ),
    ]
