# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VariantDatabase', '0002_batch_batch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='vcf_file',
            field=models.FilePathField(path='/home/cuser/Documents/Project/Preliminary'),
        ),
    ]
