# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VariantDatabase', '0002_variantinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantinformation',
            name='label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
