# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VariantDatabase', '0002_classificationcode_interpretation_question_useranswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worksheetstatusupdate',
            old_name='sample',
            new_name='worksheet',
        ),
    ]
