# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VariantDatabase', '0002_auto_20170530_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportvariant',
            name='status',
            field=models.CharField(choices=[('1', 'None'), ('2', 'Pathogenic'), ('3', 'Benign'), ('4', 'VUS')], max_length=1),
        ),
    ]
