# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VariantDatabase', '0002_auto_20170621_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadLaneQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.IntegerField()),
                ('lane', models.IntegerField()),
                ('yield_g', models.FloatField()),
                ('density', models.FloatField()),
                ('cluster_count_pf', models.FloatField()),
                ('cluster_count', models.FloatField()),
                ('phasing', models.FloatField()),
                ('prephasing', models.FloatField()),
                ('read_count', models.FloatField()),
                ('reads_pf', models.FloatField()),
                ('percent_gt_q30', models.FloatField()),
                ('percent_aligned', models.FloatField()),
                ('error_rate', models.FloatField()),
                ('error_rate_35', models.FloatField()),
                ('error_rate_50', models.FloatField()),
                ('error_rate_75', models.FloatField()),
                ('error_rate_100', models.FloatField()),
                ('workbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VariantDatabase.Worksheet')),
            ],
        ),
    ]
