# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VariantDatabase', '0003_readlanequality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readlanequality',
            name='error_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='readlanequality',
            name='error_rate_100',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='readlanequality',
            name='error_rate_35',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='readlanequality',
            name='error_rate_50',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='readlanequality',
            name='error_rate_75',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='readlanequality',
            name='percent_aligned',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='readlanequality',
            name='percent_gt_q30',
            field=models.FloatField(null=True),
        ),
    ]
