# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VariantDatabase', '0004_usersetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersetting',
            old_name='column_display',
            new_name='variant_information',
        ),
        migrations.RenameField(
            model_name='variantinformation',
            old_name='displayable_data',
            new_name='information',
        ),
    ]
