# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VariantDatabase', '0004_auto_20170627_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readlanequality',
            old_name='workbook',
            new_name='worksheet',
        ),
    ]
