# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VariantDatabase', '0006_auto_20170629_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='status',
            field=models.CharField(choices=[('1', 'New Worksheet - Awaiting Sequencing'), ('2', 'Awaiting QC Check'), ('3', 'Analysis Underway'), ('4', 'Complete'), ('5', 'Failed')], max_length=1),
        ),
    ]
