# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VariantDatabase', '0007_auto_20170314_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='variant_hash',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
