# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VariantDatabase', '0008_auto_20170704_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='acgt_cycles_image',
            field=models.FileField(null=True, upload_to='uploads/%y/%m/'),
        ),
        migrations.AddField(
            model_name='sample',
            name='coverage_image',
            field=models.FileField(null=True, upload_to='uploads/%y/%m/'),
        ),
        migrations.AddField(
            model_name='sample',
            name='gc_content_image',
            field=models.FileField(null=True, upload_to='uploads/%y/%m/'),
        ),
        migrations.AddField(
            model_name='sample',
            name='gc_depth_image',
            field=models.FileField(null=True, upload_to='uploads/%y/%m/'),
        ),
        migrations.AddField(
            model_name='sample',
            name='indel_cycles_image',
            field=models.FileField(null=True, upload_to='uploads/%y/%m/'),
        ),
        migrations.AddField(
            model_name='sample',
            name='indel_dist_image',
            field=models.FileField(null=True, upload_to='uploads/%y/%m/'),
        ),
        migrations.AddField(
            model_name='sample',
            name='insert_size_image',
            field=models.FileField(null=True, upload_to='uploads/%y/%m/'),
        ),
        migrations.AddField(
            model_name='sample',
            name='quality_cycle_image',
            field=models.FileField(null=True, upload_to='uploads/%y/%m/'),
        ),
        migrations.AddField(
            model_name='sample',
            name='quality_cycle_read_freq_image',
            field=models.FileField(null=True, upload_to='uploads/%y/%m/'),
        ),
        migrations.AddField(
            model_name='sample',
            name='quality_cycle_read_image',
            field=models.FileField(null=True, upload_to='uploads/%y/%m/'),
        ),
        migrations.AddField(
            model_name='sample',
            name='quality_heatmap_image',
            field=models.FileField(null=True, upload_to='uploads/%y/%m/'),
        ),
    ]
