# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VariantDatabase', '0009_auto_20170704_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='average_quality',
            field=models.FloatField(null=True),
        ),
    ]
