# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VariantDatabase', '0011_auto_20170704_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='acgt_cycles_image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%y/%m/'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='coverage_image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%y/%m/'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='gc_content_image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%y/%m/'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='gc_depth_image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%y/%m/'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='indel_cycles_image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%y/%m/'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='indel_dist_image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%y/%m/'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='insert_size_image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%y/%m/'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='quality_cycle_image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%y/%m/'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='quality_cycle_read_freq_image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%y/%m/'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='quality_cycle_read_image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%y/%m/'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='quality_heatmap_image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%y/%m/'),
        ),
    ]
